
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emili
 */
public class DeliveryPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryPrincipal
     */
    public DeliveryPrincipal() {
        pack();
        initComponents();
        
        //panels
        p_InicioA.setVisible(false);
    }

    public boolean UsuarioExiste(String usuario){
        for (int i = 0; i < user.size(); i++) {
            if (usuario.equals(user.get(i).getNombreU())) {
                return true;
            }
        }
        return false;
        //Sip, es el mismo metodo que use en el laboratorio Anterior, y tal vez de los labs mas viejitos
        
    }
    public boolean Entrar(String usuario, String password){
        usuario = tf_nombreUsuarioIS.getText();
        password = pf_passwordUsuarioIS.getText();
        for (Usuarios usuarios : user) {
            if (usuario.equals(usuarios.getNombreU()) && password.equals(usuarios.getPassword())) {
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d_crearCuentaU = new javax.swing.JDialog();
        p_crearCU = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        tf_crearNombreOGU = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_crearNombreUsuarioU = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_crearPassword = new javax.swing.JTextField();
        b_crearUsuario = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        b_volverU = new javax.swing.JButton();
        d_crearCuentaA = new javax.swing.JDialog();
        p_crearCA = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_crearPasswordA = new javax.swing.JTextField();
        tf_crearNombreOGA = new javax.swing.JTextField();
        tf_crearNombreUsuarioA = new javax.swing.JTextField();
        b_volverAdmin = new javax.swing.JButton();
        b_crearAdmin = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        d_pantallaUsuario = new javax.swing.JDialog();
        p_deCliente = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tf_mostrarNombre = new javax.swing.JTextField();
        tp_bienvenidoCliente = new javax.swing.JTabbedPane();
        p_nombreRestaurantes = new javax.swing.JPanel();
        p_realizarCompras = new javax.swing.JPanel();
        p_comprasRecientes = new javax.swing.JPanel();
        d_pantallaAdmin = new javax.swing.JDialog();
        p_bienvenidoAdmin = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tf_mostrarNombre1 = new javax.swing.JTextField();
        tp_deAdmin = new javax.swing.JTabbedPane();
        p_crearRestaurantes = new javax.swing.JPanel();
        p_visualizarDatos = new javax.swing.JPanel();
        p_top5Res = new javax.swing.JPanel();
        p_top5U = new javax.swing.JPanel();
        p_InicioU = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreUsuarioIS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pf_passwordUsuarioIS = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        b_accederU = new javax.swing.JButton();
        b_entrarAdmin = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        b_paraCrearUser = new javax.swing.JButton();
        p_InicioA = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tf_nombreAdmin = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        pf_passwordAdmin = new javax.swing.JPasswordField();
        b_entrarUsuario = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        b_paraCrearAdmin = new javax.swing.JButton();
        b_accederA = new javax.swing.JButton();

        d_crearCuentaU.setMinimumSize(new java.awt.Dimension(700, 400));
        d_crearCuentaU.setPreferredSize(new java.awt.Dimension(700, 400));
        d_crearCuentaU.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_crearCU.setBackground(new java.awt.Color(255, 255, 255));
        p_crearCU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_crearCU.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCU.setMinimumSize(new java.awt.Dimension(700, 400));
        p_crearCU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Crear Usuario");
        p_crearCU.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        p_crearCU.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 640, 10));

        tf_crearNombreOGU.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearNombreOGU.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearNombreOGU.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCU.add(tf_crearNombreOGU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 310, -1));

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre Original: ");
        p_crearCU.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre Usuario: ");
        p_crearCU.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tf_crearNombreUsuarioU.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearNombreUsuarioU.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearNombreUsuarioU.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCU.add(tf_crearNombreUsuarioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 310, -1));

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Password:");
        p_crearCU.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        tf_crearPassword.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearPassword.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearPassword.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCU.add(tf_crearPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 370, -1));

        b_crearUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_crearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        b_crearUsuario.setText("Crear");
        b_crearUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_crearUsuario.setContentAreaFilled(false);
        b_crearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearUsuarioActionPerformed(evt);
            }
        });
        p_crearCU.add(b_crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 100, -1));

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_crearCU.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 20, 40));

        b_volverU.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_volverU.setForeground(new java.awt.Color(0, 0, 0));
        b_volverU.setText("Volver");
        b_volverU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_volverU.setContentAreaFilled(false);
        b_volverU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_volverU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverUActionPerformed(evt);
            }
        });
        p_crearCU.add(b_volverU, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 60, -1));

        d_crearCuentaU.getContentPane().add(p_crearCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_crearCuentaA.setMinimumSize(new java.awt.Dimension(700, 400));
        d_crearCuentaA.setPreferredSize(new java.awt.Dimension(700, 400));
        d_crearCuentaA.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_crearCA.setBackground(new java.awt.Color(255, 255, 255));
        p_crearCA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_crearCA.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCA.setMinimumSize(new java.awt.Dimension(700, 400));
        p_crearCA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");
        p_crearCA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Crear Admin");
        p_crearCA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre Original: ");
        p_crearCA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre Usuario: ");
        p_crearCA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tf_crearPasswordA.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearPasswordA.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearPasswordA.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCA.add(tf_crearPasswordA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 370, -1));

        tf_crearNombreOGA.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearNombreOGA.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearNombreOGA.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCA.add(tf_crearNombreOGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 310, -1));

        tf_crearNombreUsuarioA.setBackground(new java.awt.Color(255, 255, 255));
        tf_crearNombreUsuarioA.setFont(new java.awt.Font("Maiandra GD", 0, 15)); // NOI18N
        tf_crearNombreUsuarioA.setForeground(new java.awt.Color(0, 0, 0));
        p_crearCA.add(tf_crearNombreUsuarioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 310, -1));

        b_volverAdmin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_volverAdmin.setForeground(new java.awt.Color(0, 0, 0));
        b_volverAdmin.setText("Volver");
        b_volverAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_volverAdmin.setContentAreaFilled(false);
        b_volverAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_volverAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverAdminActionPerformed(evt);
            }
        });
        p_crearCA.add(b_volverAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 60, -1));

        b_crearAdmin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_crearAdmin.setForeground(new java.awt.Color(0, 0, 0));
        b_crearAdmin.setText("Crear");
        b_crearAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_crearAdmin.setContentAreaFilled(false);
        b_crearAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_crearAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crearAdminActionPerformed(evt);
            }
        });
        p_crearCA.add(b_crearAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 100, -1));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_crearCA.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 20, 40));
        p_crearCA.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 640, 10));

        d_crearCuentaA.getContentPane().add(p_crearCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_pantallaUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_deCliente.setBackground(new java.awt.Color(0, 0, 0));
        p_deCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_deCliente.setForeground(new java.awt.Color(255, 255, 255));
        p_deCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel15.setForeground(null);
        jLabel15.setText("Bienvendio Cliente: ");
        p_deCliente.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        tf_mostrarNombre.setBackground(new java.awt.Color(0, 0, 0));
        tf_mostrarNombre.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        tf_mostrarNombre.setForeground(new java.awt.Color(245, 245, 245));
        tf_mostrarNombre.setBorder(null);
        tf_mostrarNombre.setEnabled(false);
        p_deCliente.add(tf_mostrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 22, 300, 30));

        tp_bienvenidoCliente.setBackground(new java.awt.Color(0, 0, 0));
        tp_bienvenidoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tp_bienvenidoCliente.setForeground(new java.awt.Color(255, 255, 255));

        p_nombreRestaurantes.setBackground(new java.awt.Color(0, 0, 0));
        p_nombreRestaurantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_nombreRestaurantes.setForeground(new java.awt.Color(255, 255, 255));
        p_nombreRestaurantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_bienvenidoCliente.addTab("Nombre de Restaurantes", p_nombreRestaurantes);

        p_realizarCompras.setBackground(new java.awt.Color(0, 0, 0));
        p_realizarCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_realizarCompras.setForeground(new java.awt.Color(255, 255, 255));
        p_realizarCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_bienvenidoCliente.addTab("Realizar Compras", p_realizarCompras);

        p_comprasRecientes.setBackground(new java.awt.Color(0, 0, 0));
        p_comprasRecientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_comprasRecientes.setForeground(new java.awt.Color(255, 255, 255));
        p_comprasRecientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_bienvenidoCliente.addTab("Compras Recientes", p_comprasRecientes);

        p_deCliente.add(tp_bienvenidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 340));

        d_pantallaUsuario.getContentPane().add(p_deCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        d_pantallaAdmin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_bienvenidoAdmin.setBackground(new java.awt.Color(0, 0, 0));
        p_bienvenidoAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_bienvenidoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        p_bienvenidoAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel16.setText("Bienvendio Admin: ");
        p_bienvenidoAdmin.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        tf_mostrarNombre1.setBackground(new java.awt.Color(0, 0, 0));
        tf_mostrarNombre1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        tf_mostrarNombre1.setForeground(new java.awt.Color(245, 245, 245));
        tf_mostrarNombre1.setBorder(null);
        tf_mostrarNombre1.setEnabled(false);
        p_bienvenidoAdmin.add(tf_mostrarNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 22, 300, 30));

        tp_deAdmin.setBackground(new java.awt.Color(0, 0, 0));
        tp_deAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tp_deAdmin.setForeground(new java.awt.Color(255, 255, 255));

        p_crearRestaurantes.setBackground(new java.awt.Color(0, 0, 0));
        p_crearRestaurantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_crearRestaurantes.setForeground(new java.awt.Color(255, 255, 255));
        p_crearRestaurantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_deAdmin.addTab("Crear Restaurante", p_crearRestaurantes);

        p_visualizarDatos.setBackground(new java.awt.Color(0, 0, 0));
        p_visualizarDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_visualizarDatos.setForeground(new java.awt.Color(255, 255, 255));
        p_visualizarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_deAdmin.addTab("Visualizar Datos", p_visualizarDatos);

        p_top5Res.setBackground(new java.awt.Color(0, 0, 0));
        p_top5Res.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_top5Res.setForeground(new java.awt.Color(255, 255, 255));
        p_top5Res.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_deAdmin.addTab("Top 5 Restaurantes mas exitosos", p_top5Res);

        p_top5U.setBackground(new java.awt.Color(0, 0, 0));
        p_top5U.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        p_top5U.setForeground(new java.awt.Color(255, 255, 255));
        p_top5U.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tp_deAdmin.addTab("Top 5 Usuarios con mas Compras", p_top5U);

        p_bienvenidoAdmin.add(tp_deAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 340));

        d_pantallaAdmin.getContentPane().add(p_bienvenidoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_InicioU.setBackground(new java.awt.Color(255, 255, 255));
        p_InicioU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_InicioU.setForeground(new java.awt.Color(0, 0, 0));
        p_InicioU.setMinimumSize(new java.awt.Dimension(700, 400));
        p_InicioU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Password");
        p_InicioU.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Iniciar Sesion Usuario");
        p_InicioU.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        tf_nombreUsuarioIS.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreUsuarioIS.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        tf_nombreUsuarioIS.setForeground(new java.awt.Color(0, 0, 0));
        p_InicioU.add(tf_nombreUsuarioIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 430, -1));
        p_InicioU.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 660, 10));
        p_InicioU.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 520, 10));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de Usuario");
        p_InicioU.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        pf_passwordUsuarioIS.setBackground(new java.awt.Color(255, 255, 255));
        pf_passwordUsuarioIS.setForeground(new java.awt.Color(0, 0, 0));
        pf_passwordUsuarioIS.setText("jPasswordField1");
        p_InicioU.add(pf_passwordUsuarioIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 430, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_InicioU.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 20, 50));

        b_accederU.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_accederU.setForeground(new java.awt.Color(0, 0, 0));
        b_accederU.setText("Acceder");
        b_accederU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_accederU.setContentAreaFilled(false);
        b_accederU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_accederU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_accederUActionPerformed(evt);
            }
        });
        p_InicioU.add(b_accederU, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        b_entrarAdmin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_entrarAdmin.setForeground(new java.awt.Color(0, 0, 0));
        b_entrarAdmin.setText("Iniciar Sesion Como Admin");
        b_entrarAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_entrarAdmin.setContentAreaFilled(false);
        b_entrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_entrarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_entrarAdminActionPerformed(evt);
            }
        });
        p_InicioU.add(b_entrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));
        p_InicioU.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 520, 10));

        b_paraCrearUser.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_paraCrearUser.setForeground(new java.awt.Color(0, 0, 0));
        b_paraCrearUser.setText("Crear una Cuenta como Usuario");
        b_paraCrearUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_paraCrearUser.setContentAreaFilled(false);
        b_paraCrearUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_paraCrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_paraCrearUserActionPerformed(evt);
            }
        });
        p_InicioU.add(b_paraCrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        getContentPane().add(p_InicioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        p_InicioA.setBackground(new java.awt.Color(255, 255, 255));
        p_InicioA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_InicioA.setForeground(new java.awt.Color(0, 0, 0));
        p_InicioA.setMinimumSize(new java.awt.Dimension(700, 400));
        p_InicioA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Iniciar Sesion Admin");
        p_InicioA.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre de Usuario");
        p_InicioA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        p_InicioA.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 520, 10));

        tf_nombreAdmin.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreAdmin.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        tf_nombreAdmin.setForeground(new java.awt.Color(0, 0, 0));
        p_InicioA.add(tf_nombreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 430, -1));
        p_InicioA.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 660, 10));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");
        p_InicioA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));
        p_InicioA.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 520, 10));

        pf_passwordAdmin.setBackground(new java.awt.Color(255, 255, 255));
        pf_passwordAdmin.setForeground(new java.awt.Color(0, 0, 0));
        pf_passwordAdmin.setText("jPasswordField1");
        p_InicioA.add(pf_passwordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 430, 30));

        b_entrarUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_entrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        b_entrarUsuario.setText("Iniciar Sesion Como Usuario");
        b_entrarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_entrarUsuario.setContentAreaFilled(false);
        b_entrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_entrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_entrarUsuarioActionPerformed(evt);
            }
        });
        p_InicioA.add(b_entrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        p_InicioA.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 20, 50));

        b_paraCrearAdmin.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_paraCrearAdmin.setForeground(new java.awt.Color(0, 0, 0));
        b_paraCrearAdmin.setText("Crear una Cuenta como Admin");
        b_paraCrearAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_paraCrearAdmin.setContentAreaFilled(false);
        b_paraCrearAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_paraCrearAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_paraCrearAdminActionPerformed(evt);
            }
        });
        p_InicioA.add(b_paraCrearAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        b_accederA.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        b_accederA.setForeground(new java.awt.Color(0, 0, 0));
        b_accederA.setText("Acceder");
        b_accederA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b_accederA.setContentAreaFilled(false);
        b_accederA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_accederA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_accederAActionPerformed(evt);
            }
        });
        p_InicioA.add(b_accederA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        getContentPane().add(p_InicioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_entrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarAdminActionPerformed
        p_InicioA.setVisible(true);
        p_InicioU.setVisible(false);
    }//GEN-LAST:event_b_entrarAdminActionPerformed

    private void b_paraCrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_paraCrearUserActionPerformed
        d_crearCuentaU.pack();
        d_crearCuentaU.setVisible(true);
        d_crearCuentaU.setLocationRelativeTo(this);
    }//GEN-LAST:event_b_paraCrearUserActionPerformed

    private void b_entrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_entrarUsuarioActionPerformed
        p_InicioA.setVisible(false);
        p_InicioU.setVisible(true);        
    }//GEN-LAST:event_b_entrarUsuarioActionPerformed

    private void b_paraCrearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_paraCrearAdminActionPerformed
        d_crearCuentaA.pack();
        d_crearCuentaA.setVisible(true);
        d_crearCuentaA.setLocationRelativeTo(this);        
    }//GEN-LAST:event_b_paraCrearAdminActionPerformed

    private void b_volverUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverUActionPerformed
        d_crearCuentaU.setVisible(false);
        d_crearCuentaU.setLocationRelativeTo(null);
        p_InicioU.setVisible(true);
        p_InicioA.setVisible(false);        
    }//GEN-LAST:event_b_volverUActionPerformed

    private void b_volverAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverAdminActionPerformed
        d_crearCuentaA.setVisible(false);
        d_crearCuentaA.setLocationRelativeTo(null);
        p_InicioA.setVisible(true);
        p_InicioU.setVisible(false);        
    }//GEN-LAST:event_b_volverAdminActionPerformed

    private void b_accederUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_accederUActionPerformed
        String nombreU = tf_nombreUsuarioIS.getText();
        String password = pf_passwordUsuarioIS.getText();
        if (Entrar(nombreU, password)) {
            d_pantallaUsuario.pack();
            d_pantallaUsuario.setVisible(true);
            d_pantallaUsuario.setLocationRelativeTo(this);
        }else{
            JOptionPane.showMessageDialog(this, "Nombre de Usuario o password incorrecto\n\n"
                    + "Vuelva a intentarlo");
        }
    }//GEN-LAST:event_b_accederUActionPerformed

    private void b_accederAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_accederAActionPerformed
        String nombreU = tf_nombreUsuarioIS.getText();
        String password = pf_passwordUsuarioIS.getText();
        if (Entrar(nombreU, password)) {
            d_pantallaAdmin.pack();
            d_pantallaAdmin.setVisible(true);
            d_pantallaAdmin.setLocationRelativeTo(this);
        }else{
            JOptionPane.showMessageDialog(this, "Nombre de Usuario o password incorrecto\n\n"
                    + "Vuelva a intentarlo");
        }       
    }//GEN-LAST:event_b_accederAActionPerformed

    private void b_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearUsuarioActionPerformed
        String nombreO = tf_crearNombreOGU.getText();
        String nombreU = tf_crearNombreUsuarioU.getText();
        String password = tf_crearPassword.getText();
        
        if (nombreO.equals("") || nombreU.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Llene todas las casillas porfavor");
        }else{
            if (UsuarioExiste(nombreU)) {
            JOptionPane.showMessageDialog(this, "Ya existe un usuario con el nombre de "+nombreU);                
            }else{
                tf_crearNombreOGU.setText("");
                tf_crearNombreUsuarioU.setText("");
                tf_crearPassword.setText("");
                d_crearCuentaU.setVisible(false);
                d_crearCuentaU.setLocationRelativeTo(null);
                int saldo = 0;
                Usuarios u = new Usuarios (nombreO, nombreU, password, saldo);
                user.add(u);
            }
        }
    }//GEN-LAST:event_b_crearUsuarioActionPerformed

    private void b_crearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crearAdminActionPerformed
        String nombreO = tf_crearNombreOGA.getText();
        String nombreU = tf_crearNombreUsuarioA.getText();
        String password = tf_crearPasswordA.getText();
        
        if (nombreO.equals("") || nombreU.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Llene todas las casillas porfavor");
        }else{
            if (UsuarioExiste(nombreU)) {
            JOptionPane.showMessageDialog(this, "Ya existe un usuario con el nombre de "+nombreU);                
            }else{
                tf_crearNombreOGA.setText("");
                tf_crearNombreUsuarioA.setText("");
                tf_crearPasswordA.setText("");
                d_crearCuentaA.setVisible(false);
                d_crearCuentaA.setLocationRelativeTo(null);
                int saldo = 0;
                Usuarios u = new Usuarios (nombreO, nombreU, password, saldo);
                user.add(u);                
            }
        }        
    }//GEN-LAST:event_b_crearAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryPrincipal().setVisible(true);
            }
        });
    }

    
    ArrayList<Usuarios> user = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_accederA;
    private javax.swing.JButton b_accederU;
    private javax.swing.JButton b_crearAdmin;
    private javax.swing.JButton b_crearUsuario;
    private javax.swing.JButton b_entrarAdmin;
    private javax.swing.JButton b_entrarUsuario;
    private javax.swing.JButton b_paraCrearAdmin;
    private javax.swing.JButton b_paraCrearUser;
    private javax.swing.JButton b_volverAdmin;
    private javax.swing.JButton b_volverU;
    private javax.swing.JDialog d_crearCuentaA;
    private javax.swing.JDialog d_crearCuentaU;
    private javax.swing.JDialog d_pantallaAdmin;
    private javax.swing.JDialog d_pantallaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel p_InicioA;
    private javax.swing.JPanel p_InicioU;
    private javax.swing.JPanel p_bienvenidoAdmin;
    private javax.swing.JPanel p_comprasRecientes;
    private javax.swing.JPanel p_crearCA;
    private javax.swing.JPanel p_crearCU;
    private javax.swing.JPanel p_crearRestaurantes;
    private javax.swing.JPanel p_deCliente;
    private javax.swing.JPanel p_nombreRestaurantes;
    private javax.swing.JPanel p_realizarCompras;
    private javax.swing.JPanel p_top5Res;
    private javax.swing.JPanel p_top5U;
    private javax.swing.JPanel p_visualizarDatos;
    private javax.swing.JPasswordField pf_passwordAdmin;
    private javax.swing.JPasswordField pf_passwordUsuarioIS;
    private javax.swing.JTextField tf_crearNombreOGA;
    private javax.swing.JTextField tf_crearNombreOGU;
    private javax.swing.JTextField tf_crearNombreUsuarioA;
    private javax.swing.JTextField tf_crearNombreUsuarioU;
    private javax.swing.JTextField tf_crearPassword;
    private javax.swing.JTextField tf_crearPasswordA;
    private javax.swing.JTextField tf_mostrarNombre;
    private javax.swing.JTextField tf_mostrarNombre1;
    private javax.swing.JTextField tf_nombreAdmin;
    private javax.swing.JTextField tf_nombreUsuarioIS;
    private javax.swing.JTabbedPane tp_bienvenidoCliente;
    private javax.swing.JTabbedPane tp_deAdmin;
    // End of variables declaration//GEN-END:variables
}
